### ISSUE TITLE
Create back-end structure

### ISSUE THREAD

**Issue by n1md7** [n1md7/card-game#2]
Setup node project.

Use Koa.js as a BE framework.

Folder structure
```yaml
src:
  assets:
    css
    img 
  js:
  test:
    unit
    ui
```
